#ifndef TIPODETOKEN_H
#define TIPODETOKEN_H

enum class TipoDeToken
{
    NUMERO_INTEIRO,
    OPERADOR_ARITMETICO,
    IDENTIFICADOR,
    PONTO_E_VIRGULA,
    ABRE_PARENTESES,
    FECHA_PARENTESES,
    ABRE_CHAVES,
    FECHA_CHAVES,
    ABRE_COLCHETES,
    FECHA_COLCHETES,
    VIRGULA,
    OPERADOR_ATRIBUICAO,
    PALAVRA_RESERVADA,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    NUMERO_REAL,
    STRING,
    INCREMENTO,
    DECREMENTO,
    PONTO,
    DOIS_PONTOS,
    INTERROGACAO,
    DESCONHECIDO
};

#endif
